# Generated by Django 3.1.4 on 2020-12-07 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201207_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='quantity',
        ),
    ]
